server:
  port: 8080
  # ssl: 
  #   key-store: classpath:keystore.p12
  #   key-store-password: 123456
  #   keyStoreType: PKCS12
  #   keyAlias: tomcat
    
spring:
  application:
    name: admin-managee
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: "jdbc:mysql://localhost:3306/book_shop"
    username: root
    password: password    
  resources:
    static-locations:
    - classpath:static/
    - file:external/
    